services:
  phpserver:
    image: uselagoon/php-8.1-cli-drupal:23.10.0
    volumes:
      - .:/app:delegated
    environment:
      # To enable xdebug: XDEBUG_ENABLE=true docker compose up -d phpserver
      XDEBUG_ENABLE: ${XDEBUG_ENABLE:-}
  chrome:
    image: selenium/standalone-chrome:118.0
