services:
  phpserver:
    image: uselagoon/php-8.2-cli:24.10.0
    volumes:
      - .:/app:delegated
    environment:
      # To enable xdebug: XDEBUG_ENABLE=true docker compose up -d phpserver
      XDEBUG_ENABLE: ${XDEBUG_ENABLE:-}
  chrome:
    image: selenium/standalone-chromium:130.0
