version: 2
jobs:
  build:
    working_directory: /root/project
    docker:
      - image: drevops/ci-runner:24.4.0
        environment:
          COMPOSER_ALLOW_SUPERUSER: 1
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Validate Composer configuration
          command: composer validate --ansi --strict
      - run:
          name: Start containers
          command: docker compose up -d --build
      - run:
          name: Copy codebase into container
          command: docker cp -L . $(docker compose ps -q phpserver):/app/
      - run:
          name: Install dev dependencies
          command: docker compose exec phpserver composer install --ansi --no-suggest
      - run:
          name: Lint code
          command: docker compose exec phpserver composer lint
      - run:
          name: Restart server with Xdebug enabled
          command: XDEBUG_ENABLE=true docker compose up -d phpserver
      - run:
          name: Run tests with PHPUnit
          command: docker compose exec -T -e XDEBUG_MODE=coverage phpserver vendor/bin/phpunit
      - run:
          name: Run tests with Behat
          command: docker compose exec -T -e XDEBUG_MODE=coverage phpserver vendor/bin/behat
      - run:
          name: Process test logs and artifacts
          command: |
            mkdir -p /tmp/test_results
            mkdir -p /tmp/artifacts
            if docker compose ps --services --filter "status=running" | grep -q phpserver && docker compose exec phpserver test -d /app/.logs; then
              docker compose cp phpserver:/app/.logs/. "/tmp/artifacts/"
              if docker compose exec -T phpserver sh -c 'test -d /app/.logs/test_results'; then
                 docker compose cp phpserver:/app/.logs/test_results/. "/tmp/test_results/"
              fi
            fi
          when: always
      - store_test_results:
          path: /tmp/test_results
      - store_artifacts:
          path: /tmp/artifacts
      - run:
          name: Upload code coverage reports to Codecov
          command: if [ -d /tmp/artifacts/coverage ]; then codecov -Z -s /tmp/artifacts/coverage; fi
