name: Draft release notes

on:
  push:
    tags:
      - '*'
    branches:
      - main

permissions:
  contents: write

jobs:
  release-drafter:
    permissions:
      contents: write
      pull-requests: write

    runs-on: ubuntu-latest

    steps:
      - name: Draft release notes
        uses: release-drafter/release-drafter@44a942e465867c7465b76aa808ddca6e0acae5da # v7
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
